const data = {
    products: [
        {
            _id: '1',
            name: 'Ốp lưng iPhone 12 Mini nhựa dẻo Gấu',
            category: 'op-lung',
            image: '../images/product-1.jpg',
            price: '150.000 VNĐ',
            countInStock: 10,
            brand: 'Iphone',
            rating: 4.5,
            numReviews: 10,
            description: 'Kiểu dáng thời trang và đẹp mắt. Thiết kế vừa vặn và ôm sát thân máy. Dễ dàng tháo/lắp ốp vào máy.',
        },
        {
            _id: '2',
            name: 'CÁP SẠC IPHONE 2 mét X14',
            category: 'sac-cap',
            image: '../images/product-2.jpg',
            price: '80.000 VNĐ',
            countInStock: 10,
            brand: 'Micro Hoco',
            rating: 4,
            numReviews: 10,
            description: 'Cáp sạc dây dù Micro Hoco X14 2 mét mang đến sự hiện đại và sang trọng một chiếc cáp sạc không chỉ tương thích với thiết bị của mình mà còn đẹp, bền, sang trọng, cao cấp. Chất liệu dù bọc ngoài, đầu cáp chắc chắn.',
        },
        {
            _id: '3',
            name: 'Sạc dự phòng mini',
            category: 'sac-dtdd',
            image: '../images/product-3.jpg',
            price: '300.000 VNĐ',
            countInStock: 10,
            brand: 'HOCO',
            rating: 3,
            numReviews: 10,
            description: 'Dung lượng 10.000 mah - có màn hình hiển thị % pin - có 2 cổng sạc tiện lợi.',
        },
        {
            _id: '4',
            name: 'Tai nghe Bluetooth True Wireless OPPO ENCO Buds ETI81',
            category: 'tai-nghe',
            image: '../images/product-4.jpg',
            price: '750.000 VNĐ',
            countInStock: 10,
            brand: 'OPPO',
            rating: 3.5,
            numReviews: 10,
            description: 'Bề mặt housing và hộp sạc được bao phủ bởi sắc trắng trang nhã, thanh thuần, housing dạng công thái học kết hợp đệm tai silicone mềm nhẹ (có 3 kích thước) giúp người dùng đeo tai nghe Bluetooth thoải mái cả ngày.',
        },
        {
            _id: '5',
            name: 'Ốp lưng iPhone XS Max Nhựa dẻo Nake Slim JM nude',
            category: 'op-lung',
            image: '../images/product-5.jpg',
            price: '50.000 VNĐ',
            countInStock: 10,
            brand: 'Iphone',
            rating: 4,
            numReviews: 10,
            description: 'Ốp lưng trong suốt, phù hợp cà nam và nữ. Thiết kế vỏ nhựa dẻo bền bỉ, vừa vặn và ôm sát thân máy. Dễ dàng tháo/lắp ốp vào máy.',
        },
        {
            _id: '6',
            name: 'Cáp Lightning 1m Apple MXLY2 Trắng',
            category: 'sac-cap',
            image: '../images/product-6.jpg',
            price: '450.000 VNĐ',
            countInStock: 10,
            brand: 'Apple',
            rating: 5,
            numReviews: 10,
            description: 'Cáp Lightning 1m Apple MXLY2 trắng có thiết kế đơn giản với chiều dài 1 m, thích hợp dùng trong nhiều trường hợp khác nhau.',
        },
        {
            _id: '7',
            name: 'Pin sạc dự phòng Polymer 10.000 mAh Type C PD Anker PowerCore Slim A1231',
            category: 'sac-dtdd',
            image: '../images/product-7.jpg',
            price: '700.000 VNĐ',
            countInStock: 10,
            brand: 'ANKER',
            rating: 4,
            numReviews: 10,
            description: 'Pin dự phòng được thiết kế vừa tay, khi cầm tạo cảm giác chắc chắn, vỏ của pin được phủ một lớp vải Fabric bền bỉ vừa nâng cao vẻ đẹp bên ngoài vừa bảo vệ tốt các linh kiện bên trong.',
        },
        {
            _id: '8',
            name: 'Tai nghe Bluetooth True Wireless Xiaomi Earbuds Basic 2 BHR4272GL',
            category: 'tai-nghe',
            image: '../images/product-8.jpg',
            price: '650.000 VNĐ',
            countInStock: 10,
            brand: 'Xiaomi',
            rating: 3.5,
            numReviews: 10,
            description: 'Tai nghe có kích thước nhỏ gọn chỉ nặng 35.4 g không hề nặng tai khi sử dụng lâu. Tai nghe tặng kèm 2 nút đệm tai với kích thước khác nhau giúp bạn dễ dàng lựa chọn phù hợp với tai tránh lỏng lẻo, rơi rớt.',
        },
        {
            _id: '9',
            name: 'Ốp lưng iPhone 12 Nhựa cứng viền dẻo Berty JM Hồng Xanh',
            category: 'op-lung',
            image: '../images/product-9.jpg',
            price: '100.000 VNĐ',
            countInStock: 10,
            brand: 'Iphone',
            rating: 4.5,
            numReviews: 10,
            description: 'Kiểu dáng thời trang và đẹp mắt. Thiết kế vừa vặn và ôm sát thân máy. Dễ dàng tháo/lắp ốp vào máy.',
        },
        {
            _id: '10',
            name: 'Cáp Type C - Type C 0.9m Anker PowerLine III A8852',
            category: 'sac-cap',
            image: '../images/product-10.jpg',
            price: '250.000 VNĐ',
            countInStock: 10,
            brand: 'ANKER',
            rating: 5,
            numReviews: 10,
            description: 'Anker PowerLine III A8852 cho tốc độ sạc mạnh mẽ với công suất 60W, công nghệ sạc nhanh Power Delivery.',
        },
        {
            _id: '11',
            name: 'Pin sạc dự phòng Polymer 10.000 mAh Type C Xiaomi Power Bank 3 Ultra Compact',
            category: 'sac-dtdd',
            image: '../images/product-11.jpg',
            price: '600.000 VNĐ',
            countInStock: 10,
            brand: 'Xiaomi',
            rating: 4,
            numReviews: 10,
            description: 'Pin sạc dự phòng gần như chỉ bằng 1 tấm thẻ ngân hàng, trọng lượng 200 gram, không chiếm diện tích, cho bạn dễ dàng bỏ vào túi quần, balo, túi xách và mang theo bên mình khi cần. Bề mặt phủ màu đen tuyền phong cách, có đường kẻ dọc bám tay, cầm nắm chắc chắn hơn.',
        },
        {
            _id: '8',
            name: 'Tai nghe Bluetooth True Wireless Samsung Galaxy Buds+ R175',
            category: 'tai-nghe',
            image: '../images/product-12.jpg',
            price: '1.500.000 VNĐ',
            countInStock: 10,
            brand: 'Samsung',
            rating: 5,
            numReviews: 10,
            description: 'Housing có bề mặt chất liệu nhựa bóng bền đẹp, nhìn hơi thô nhưng đeo vào khuôn tai rất vừa vặn, nút tai thiết kế hướng thẳng vào tai cho độ kín cao, nghe rõ âm thanh hơn. Hộp sạc cũng làm từ nhựa bóng, trọng lượng 6.3 g, kích thước nhỏ nhắn, nằm gọn trong tay bạn, dễ cho vào túi quần hoặc túi xách, balo mang theo khi đi chơi, đi học, du lịch,...',
        },
    ],
};
export default data;